spring:
  profiles:
    active: -dev
  application:
    name: springcloud-config-dev

---
spring:
  profiles: dev
  application:
    name: springcloud-config-dev

---
spring:
  profiles: dev
  application:
    name: springcloud-config-test